### ISSUE TITLE
Mail and IRC fmn.preference.update leads to 403

### ISSUE THREAD

**Issue by robyduck** [fedora-infra/fmn#30]
I got two notifications about updating my email and IRC filters form notifications@stg.fedoraproject.org, although I didn't update any filters (but I was added to the packager group).

fmn.preference.update -- robyduck updated their email filters https://apps.fedoraproject.org/notifications/

Following the message it explains the reason why I got the notification:
You received this message due to your preference settings at
https://apps.stg.fedoraproject.org/notifications//robyduck.id.fedoraproject.org/email/307

but when going to the link I get an 403 error:
Forbidden
You don't have the permission to access the requested resource. It is either read-protected or not readable by the server.

I guess the link should lead to the tabs which are in https://apps.stg.fedoraproject.org/notifications, and when logging in there directly I don't have any problem to access the web interface.

**Comment by pypingou** [comment]
> although I didn't update any filters (but I was added to the packager group).

The later is the reason for the former, new packager are automatically added to FMN so that they get decent notifications when they become packager (and application such as pkgdb stop sending emails on their own).

**Comment by ralphbean** [comment]
Staging shouldn't send people emails when they get added to the packager group -- only production.

**Comment by ralphbean** [comment]
This should all be fixed now.

**Comment by rkratky** [comment]
I'm still getting the 403 error when I try to open the URL [1] supplied in the notif. email. On top of that, when I open the web UI directly [2], which works fine, I see that I have no notifications enabled. Still, I'm getting the meeting minutes.

[1] https://apps.fedoraproject.org/notifications/fmnmeetingminutes.id.fedoraproject.org/email/29368
[2] https://apps.fedoraproject.org/notifications/

**Comment by ralphbean** [comment]
> I'm still getting the 403 error when I try to open the URL [1] supplied in the notif. email.

Ah, these are not being sent to you directly.  You must be getting them because you are subscribed to meetingminutes@lists.fedoraproject.org  Can you confirm?
